[tool.poetry]
name = "anicli_api"
version = "0.1.0"
description = "Anime extractor api implementation"
authors = ["Georgiy aka Vypivshiy"]
license = "MIT"
readme = "README.MD"
packages = [{include = "anicli_api"}]
exclude = ["tests/"]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.23.0"
bs4 = "^0.0.1"

[tool.poetry.group.dev.dependencies]
pytest = {extras = ["coverage"], version = "^7.2.0"}
pytest-cov = "^4.0.0"
flake8 = "^5.0.0"
mypy = "^0.982"
pytest-asyncio = "^0.20.2"
twine = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "--ignore='anicli_api.extractors.*' --cov='anicli_api._http' --cov='anicli_api.base' --cov='anicli_api.decoders' --cov='anicli_api.loader' --cov='anicli_api.random_useragent' --cov='anicli_api.re_models'"


[tool.mypy]
python_version = 3.8
exclude="(tests|venv|.venv)"
ignore_missing_imports = true
warn_no_return = false
warn_return_any = false
warn_unused_configs = true

[flake8]
exclude = '.git,__pycache__,env,venv,tests,.venv'
max-line-length = 120
max-complexity = 8
ignore = 'F405, F403, W503, E501, F401, E203'

[[tool.mypy.overrides]]
module = "tests.*"
ignore_errors = true
